void ili9225c_setPins(int sdi,int clk,int dc,int rst,int led,int cs);
void ili9225c_setBacklight(int value);
static void setDC(int value);
static void setReset(int value);
static void write(unsigned char data);
struct loadstr;
static struct loadstr ili9225c_loadman(const char* file);
static void writeCommand(unsigned char cmd);
static void writeData(unsigned char data);
static void writeRegister(unsigned char reg,unsigned int value);
static void setWindow(unsigned int x0, unsigned int y0, unsigned int x1, unsigned int y1);
static void setDisplay(int flag);
static void initBuffer();
void ili9225c_pushBuffer();
unsigned int ili9225c_getBufferPixel(unsigned int x,unsigned int y);
void ili9225c_modBuffer(unsigned char x,unsigned char y,unsigned char val);
void ili9225c_drawPixelDirect(unsigned char x,unsigned char y,unsigned int color);
void ili9225c_drawPixel(unsigned char x,unsigned char y,unsigned int color);
void ili9225c_line(int x1, int y1, int x2, int y2, unsigned int c);
void ili9225c_fillRectangle(unsigned char x1,unsigned char y1,unsigned char x2,unsigned char y2,unsigned int color);
void ili9225c_fill(unsigned int color);
void ili9225c_clear();
void ili9225c_writeImage(const char* data,int x,int y);
void ili9225c_writeImageBuffer(unsigned int** arr,int arrx,int arry,int x,int y);
void ili9225c_writeChar(char c, int x, int y);
void ili9225c_writeString(const char* data, int x, int y, int maxl, int* h);
void ili9225c_init();
void ili9225c_reset();
void ili9225c_shutdown();
void ili9225c_start();